version: '3'

services:
  backend:
    image: therhenals/thradio_backend
    build: .
    ports:
      - 3010:3010
    volumes:
      - stations_data:/backend/stations
      - db_data:/backend/db

volumes:
  stations_data:
    name: thradio_stations_data
  db_data:
    name: thradio_db_data
