version: "3"

services:
  backend:
    image: therhenals/thradio_backend
    build: .
    ports:
      - 3010:3010
    volumes:
      - stations_data:/backend/stations
      - db_data:/backend/db
    networks:
      - backend
    environment:
      - JWT_SECRET

volumes:
  stations_data:
    name: thradio_stations_data
  db_data:
    name: thradio_db_data

networks:
  backend:
    name: thradio_backend
    driver: bridge
